---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: i want to execute direct Linux command
    command: hostname -f
    register: myfirsttaskresult


  - name: i want to debug first task result
    debug:
       msg: "{{myfirsttaskresult}}"