---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present
    tags: git 

  - name: install tree
    apt:
      name: tree
      state: present
    tags: tree

  - name: install wget
    apt:
      name: wget
      state: present 
    tags: wget