---
# tasks file for mytomcatrole
- include_tasks: myuser.yml
- include_tasks: installjava.yml
- include_tasks: download.yml
- include_tasts: permission.yml
- include_tasts: tomcatDashboard.yml
- include_tasts: tomcatstart.yml
